language: node_js
node_js:
  - 8

sudo: false

install:
  - npm install

script:
  - npm run test

branches:
  only:
    - master

deploy:
  - provider: script
    script: npm run release
    on:
      branch: master
