language: node_js
node_js:
  - 10

sudo: false

install:
  - npm install

script:
  - npm run test
  - npm run build

branches:
  only:
    - master

before_deploy:
  - npm run release

deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
